### ISSUE TITLE
Question about comment

### ISSUE THREAD

**Issue by DevinR528** [rust-linting/rust-linting#12]
In this `FIXME` comment [here](https://github.com/rust-linting/rust-linting/blob/master/linter_api/src/lint.rs#L23-L24) what do you mean by driver-specific lint instances?

**Comment by xFrednet** [comment]
I've created an issue for this: https://github.com/rust-linting/design/issues/14 if that answers your question, you can close this issue. Otherwise, you're welcome to ask more questions :)

**Comment by DevinR528** [comment]
Cool thanks that makes sense, I'll close this since we now have the issue in /design#14
