### ISSUE TITLE
Add bors-ng?

### ISSUE THREAD

**Issue by xFrednet** [rust-linting/rust-linting#22]
Do we maybe want to add [bors-ng](https://github.com/apps/bors) to this repo?

I really like the stability of rust-lang repos and adding bors could ensure that we keep our master green. Since it's a free app, I think it would be a nice addition. The question is now, if everyone is okay with this.

cc @DevinR528?

**Comment by DevinR528** [comment]
Yeah sounds good to me. Probably best to start with the tools that will make it easier to manage if the project get bigger.

**Comment by xFrednet** [comment]
Perfect, then I'll add that to my todo list. I also want to make sure that the CI tests multiple targets. (I only have Linux installed)
