### ISSUE TITLE
Change lint crate loading.

### ISSUE THREAD

**Issue by xFrednet** [rust-linting/rust-linting#8]
The current lint crate loading implementation sends a trait object over a C ABI, this is AFAIK undefined behavior. Currently, it works quite well, but for the stable version a loading mechanism should be selected that uses defined behavior (and ideally only safe code), to ensure that the interface doesn't need to be changed in the future.

See [adapter docs](../tree/master/linter_adapter#implementation)

**Comment by xFrednet** [comment]
I've done some research on the topic. The current way is definitely unstable and since the type layout can change between compilation I'm surprised that it has been working without a problem so far. ^^ I believe this issue is critical, as it might affect how we can represent information for lints.

I'll create an issue for this in the design repo, as we might get some more feedback there and do some experimenting with this.

**Comment by xFrednet** [comment]
Looking into this, I feel like creating a general plugin system for Rust could be a rust-foundation grant all in itself. :sweat_smile:

**Comment by jhpratt** [comment]
It certainly could be! Plugin systems are by no means easy.

**Comment by xFrednet** [comment]
Yeah, I sadly see no good way, without a stable ABI. One option could be to introduce a stable ABI similar to `#[repr(C)]` which allows support for rust types. This should be fine when it's not the default. On the other hand, I'm far from an expert, and c/c++ has some problems that come from the chosen ABI so :shrug:.

**Comment by xFrednet** [comment]
With the lint crate api rework of #34 and #35 I believe that we can close this issue. The linter will for now use dynamic libraries. I also heard an interesting idea to potentially add static linking for static and performance focussed implementations. This is still a good idea, but I feel like that would require a discussion in the /design repo.

Problems with the FFI interface will be tracked in a new issue :upside_down_face:
